### ISSUE TITLE
Base Template

### ISSUE THREAD

**Issue by arun-esh** [arun-esh/comp3340Project#13]
![base-template](https://user-images.githubusercontent.com/59122465/179437764-de04ecc9-e6e5-4056-b19d-065210e14a4b.png)

I am proposing this base template. Let's discuss.

**Comment by arun-esh** [comment]
Editable link:
https://excalidraw.com/#room=3f277f8a7e82105cea30,NNL7APLUxwVWRGlrlXo1tA

**Comment by TanveerPoonia** [comment]
We must add site map to the footer.

**Comment by jaydeepsinh9** [comment]
I have created one login page if you guys would like to see that I would love to show you

**Comment by arun-esh** [comment]
@jaydeepsinh9 for sure. Please attach screenshot here.

**Comment by jaydeepsinh9** [comment]
![Screenshot (25)](https://user-images.githubusercontent.com/94106863/179443131-3e35ba19-cb99-486f-bcce-3002476deb79.png)

**Comment by jaydeepsinh9** [comment]
I am open for suggestions so If you guys think I can add or remove some items or create a new one

**Comment by arun-esh** [comment]
Please check the base template that I have proposed. Basically, we are going to have same header and footer for all the pages. So this login page must have that header and footer as well. 

All the html and CSS files will be going into the public folder. 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/59122465/179443573-dac7c8f6-1811-4458-ba6a-6aba73401cd9.png">

Please create another folder with name "login" under public/samples. And keep all files related to login in that folder for now.

**Comment by jaydeepsinh9** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/94106863/180613700-1f3e9c43-1afb-4d41-8f98-6b55c98b4cef.png)
![Screenshot (29)](https://user-images.githubusercontent.com/94106863/180613702-36d1e614-b07b-492d-ba14-f27025acfaca.png)
Ignore the header at this moment and yes the data base is yet to add on

**Comment by jaydeepsinh9** [comment]
I have some more ideas as well so once finished we can add more icons and a script I guess so take this if the place has wifi than only the wifi logo and box will show up
