### ISSUE TITLE
I am not able to add the login page what should I do?

### ISSUE THREAD

**Issue by TanveerPoonia** [arun-esh/comp3340Project#16]
I am not able to add the login page what should I do?

_Originally posted by @jaydeepsinh9 in https://github.com/arun-esh/comp3340Project/issues/14#issuecomment-1186715165_

**Comment by arun-esh** [comment]
@jaydeepsinh9 Please comment here.

**Comment by jaydeepsinh9** [comment]
So at this stage you are the only one who can add files?
I tried to add Login page

**Comment by jaydeepsinh9** [comment]
I am thinking to add signup page as well I think I will finish that as well

**Comment by arun-esh** [comment]
> So at this stage you are the only one who can add files?
> I tried to add Login page

This is public repo, anyone can files. The only thing is you will have to do Pull Request. We all will discuss the Pull Request, if we are agree, then it will be merged into the main project. 

Please do this:
* On the right top, there is an option to fork the repo.
* Fork this repo, it will create a new repo in your account.
* download the source code locally, and you can start working on the assigned issue.

**Comment by arun-esh** [comment]
> I am thinking to add signup page as well I think I will finish that as well

There is an issue with name base template, Please comment on that one. We will discuss there.

**Comment by arun-esh** [comment]
@jaydeepsinh9 also worth reading this one if you like
https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by arun-esh** [comment]
we discuss the options and how the backend works. I am closing this issue.
