### ISSUE TITLE
Discuss logo and Tagline for the app

### ISSUE THREAD

**Issue by arun-esh** [arun-esh/comp3340Project#17]
This App is a travel booking app where users will be able to book their desired places. 

- [x] logo
- [x] Name
- [x] tagline

**Comment by arun-esh** [comment]
Comfy Travels <-- name of the app
How it sounds like?

**Comment by TanveerPoonia** [comment]
The name sounds good but we can still think of something better in the meantime.

**Comment by HarshitOO7** [comment]
Hotels and co
Traveletro
SoVacations
TravelMore

**Comment by arun-esh** [comment]
Travelx or Traveletro ??

**Comment by TanveerPoonia** [comment]
Travelx

**Comment by jaydeepsinh9** [comment]
TravelX?

**Comment by Khushishah1812** [comment]
Travelx is good

**Comment by Khushishah1812** [comment]
We can make a logo like this
https://images.app.goo.gl/q8jc7u7pouV8q8ch6

**Comment by arun-esh** [comment]
> We can make a logo like this
> https://images.app.goo.gl/q8jc7u7pouV8q8ch6

@HarshitOO7 have a look

**Comment by arun-esh** [comment]
Name is confirmed as **TravelX**

**Comment by jaydeepsinh9** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/94106863/180615587-6485b864-098d-4f65-ad78-65316d37c2e0.png)

**Comment by jaydeepsinh9** [comment]
Any suggestion about color?

**Comment by TanveerPoonia** [comment]
Take a look at the main page and then try to fix the color so that it looks nice.

**Comment by arun-esh** [comment]
> Any suggestion about color?

we haven't decided our main app color yet.

**Comment by arun-esh** [comment]
> ![Screenshot (30)](https://user-images.githubusercontent.com/94106863/180615587-6485b864-098d-4f65-ad78-65316d37c2e0.png)

Please go ahead with this logo. And send me transparent copy of this logo and I will test on the app.

@TanveerPoonia @Khushishah1812 @HarshitOO7 Did you like the logo?

**Comment by jaydeepsinh9** [comment]
https://user-images.githubusercontent.com/94106863/180616180-784647b2-26e7-4833-9cd9-b9eb763a7b0b.mp4

**Comment by Khushishah1812** [comment]
Yes the logo is nice and for colour I think dark blue is nice

**Comment by arun-esh** [comment]
> Yes the logo is nice and for colour I think dark blue is nice

they charge money for download.

**Comment by jaydeepsinh9** [comment]
rgb(88 142 203) try this colour

**Comment by jaydeepsinh9** [comment]
it is kind of dark-light blue

**Comment by HarshitOO7** [comment]
![image](https://user-images.githubusercontent.com/51077550/180616717-863f184d-8fd5-445a-9729-680ebb6d1652.png)

**Comment by arun-esh** [comment]
![image](https://user-images.githubusercontent.com/59122465/180617323-ce0efae9-8d65-41c3-8706-b44954eb80e8.png)

**Comment by arun-esh** [comment]
All steps are taken care of.
