### ISSUE TITLE
Create logo for the app

### ISSUE THREAD

**Issue by arun-esh** [arun-esh/comp3340Project#18]
Find the details related to this issue --> [https://github.com/arun-esh/comp3340Project/issues/17#issue-1307360772](https://github.com/arun-esh/comp3340Project/issues/17#issue-1307360772) 

Please propose a logo for the APP.

**Comment by arun-esh** [comment]
let's see what others say about it.

**Comment by jaydeepsinh9** [comment]
![48d3cf8929674659ac13d5f3de538520](https://user-images.githubusercontent.com/94106863/180615437-7c20cf52-e2f9-420b-ad0c-89e48e2595cb.png)

**Comment by jaydeepsinh9** [comment]
I know it is simple

**Comment by TanveerPoonia** [comment]
Simple logo looks nice but we need to take of the color coding.

**Comment by arun-esh** [comment]
let's move our discussion to https://github.com/arun-esh/comp3340Project/issues/17

**Comment by arun-esh** [comment]
Logo is final.
