### ISSUE TITLE
Product Detailed page

### ISSUE THREAD

**Issue by arun-esh** [arun-esh/comp3340Project#23]
To get start:
![image](https://user-images.githubusercontent.com/59122465/180618322-ff5cd0c1-e1d7-4831-9f39-25226842fe31.png)

**Comment by jaydeepsinh9** [comment]
I will do this work And I am almost there to finish it

**Comment by arun-esh** [comment]
assigned to you @jaydeepsinh9

**Comment by arun-esh** [comment]
Product detailed page is somewhat ready. For other enhancements, will create separate issue.
