### ISSUE TITLE
Basic Login Page for web App

### ISSUE THREAD

**Issue by arun-esh** [arun-esh/comp3340Project#5]
- [x] Login page for the web app
- [x] Fields required:
- email
- password
- reset button
- login button

HTML page must be responsive for multiple devices.
Must include proper ID and Classes for future manipulations.

**Comment by TanveerPoonia** [comment]
I would like to work on this one.

**Comment by arun-esh** [comment]
@TanveerPoonia assigned to you.

**Comment by TanveerPoonia** [comment]
Please close this one as well.
